// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-Ffl_Yo7CsRXKlwvWE7Vzd6PHul-msk',
    appId: '1:73016899489:web:f43827903b650eb67cfde0',
    messagingSenderId: '73016899489',
    projectId: 'jot-do-6a35f',
    authDomain: 'jot-do-6a35f.firebaseapp.com',
    storageBucket: 'jot-do-6a35f.firebasestorage.app',
    measurementId: 'G-BJE574WLD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpjK9jXS8zcXxf3lWBNwmizsoovNNfiY',
    appId: '1:73016899489:android:63be69f77cc7009d7cfde0',
    messagingSenderId: '73016899489',
    projectId: 'jot-do-6a35f',
    storageBucket: 'jot-do-6a35f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QxeqWG15dAM9y1i_QQy-YGCv1fDEKpc',
    appId: '1:73016899489:ios:771f21fa56672bb57cfde0',
    messagingSenderId: '73016899489',
    projectId: 'jot-do-6a35f',
    storageBucket: 'jot-do-6a35f.firebasestorage.app',
    androidClientId: '73016899489-uf0benkbpos6f1gb7v3gdn1butqe8rgk.apps.googleusercontent.com',
    iosClientId: '73016899489-4umfh5k7re3s0grh0vdgcthss5nhrva5.apps.googleusercontent.com',
    iosBundleId: 'com.example.jotDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QxeqWG15dAM9y1i_QQy-YGCv1fDEKpc',
    appId: '1:73016899489:ios:771f21fa56672bb57cfde0',
    messagingSenderId: '73016899489',
    projectId: 'jot-do-6a35f',
    storageBucket: 'jot-do-6a35f.firebasestorage.app',
    androidClientId: '73016899489-uf0benkbpos6f1gb7v3gdn1butqe8rgk.apps.googleusercontent.com',
    iosClientId: '73016899489-4umfh5k7re3s0grh0vdgcthss5nhrva5.apps.googleusercontent.com',
    iosBundleId: 'com.example.jotDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm-Ffl_Yo7CsRXKlwvWE7Vzd6PHul-msk',
    appId: '1:73016899489:web:f9c596735c89e6577cfde0',
    messagingSenderId: '73016899489',
    projectId: 'jot-do-6a35f',
    authDomain: 'jot-do-6a35f.firebaseapp.com',
    storageBucket: 'jot-do-6a35f.firebasestorage.app',
    measurementId: 'G-7HDF7YB4Y5',
  );
}
